name: Use GitHub App
on:
  workflow_dispatch:


  push:
    paths:
    - .github/workflows/use-github-app_installation_access_token.yml

jobs:
  checkout-other-repo:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "This is the github.workspace ..."
        echo ${{ github.workspace }}

    - name: Action to generate an installation access token from long lived private key
      id: get_workflow_token
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ vars.GH_APPLICATION_ID }}
        private_key: ${{ secrets.GH_APPLICATION_KEY }}
        
    - uses: actions/checkout@v3
      with:
        token: ${{ steps.get_workflow_token.outputs.token }}
        repository: aliransari/sysops-admin-associate
    
    - name: cat the conent of the file afer checkout
      run: cat README.md
