name: Use GitHub Token in action for cross repositories access
on:
  workflow_dispatch:


  push:
    paths:
    - .github/workflows/use-github-token.yml

jobs:
  checkout-other-repo:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "This is the github.workspace ..."
        echo ${{ github.workspace }}
        
    - uses: actions/checkout@v3
      with:
        token: ${{ github.token }}
        repository: aliransari/sysops-admin-associate
    
    - name: cat the conent of the file afer checkout
      run: cat README.md
