name: Use GitHub App
on:
  workflow_dispatch:


  push:
    paths:
    - .github/workflows/use-github-app_installation_access_token.yml

jobs:
  checkout-other-repo:
    runs-on: ubuntu-latest
    steps:

    - name: Action to generate an installation access token from long lived private key
      uses: actions/create-github-app-token@v1
      id: app-token
      with:
        app-id: ${{ vars.GH_APPLICATION_ID }}
        private-key: ${{ secrets.GH_APPLICATION_KEY }}
        
    #- uses: actions/checkout@v3
    #  env:
    #    GH_TOKEN: ${{ steps.app-token.outputs.token }}
    #  with:
    #    token: ${{ steps.app-token.outputs.token }}
    #    repository: aliransari/sysops-admin-associate

    - uses: creyD/prettier_action@v4.3
      with:
          github_token: ${{ steps.app-token.outputs.token }}

    - name: cat the conent of the file afer checkout
      run: cat ${{ github_token }}
